config/routes.rb
Rails.application.routes.draw do
  resources :recipes, only: [:show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord

  CONTENT_TYPE = 'recipe'.freeze

  def self.render_all
    CONTENTFUL_CLIENT.entries(content_type: CONTENT_TYPE, include: 3) 
    # include defines how deep to go in associations
  end

  def self.render(contentful_id)
    CONTENTFUL_CLIENT.entries(content_type: CONTENT_TYPE, include: 3, 'sys.id' => contentful_id)&.first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.render_all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.render(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MsContentfulApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<div class="container pt-6">
  <div class="column pl-6 ml-6 mb-6"><h2 class="title is-2">These are Recipes specially made for you!</h2></div>

  <div class="column">
    <% @recipes.each do |recipe| %>
      <div class="content">
        <h3 class="title is-3"><%= link_to recipe.fields[:title], recipe_path(recipe.id) %></h3> 
        <img class="content" src="<%= recipe.fields[:photo].url %>" />
      </div>
    <% end %>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="container pt-6">

  <h2 class="title is-2"><%= @recipe.fields[:title] %> </h2>
  <div class="column">
    <div class="content">
      <img class="content" src="<%= @recipe.fields[:photo].url %>" />
      <h4 class="title is-4"> Description: </h4> <p><%= @recipe.description %></p>
      <h4 class="title is-4"> Chef Name: </h4> <p><%= @recipe.fields[:chef]&.name %></p>
      <div>
        <div class="tag-container">
          <h4 class="title is-4"> Tags: </h4>
          <% unless @recipe.fields[:tags].nil? %>
            <% @recipe.fields[:tags].each do |tag| %>
              <span> <%= tag.fields[:name] %> </span>
            <% end %>
          <% else %>
            <p> No tags found </p>
          <% end %>
        </div>
      </div>
      <br>
      <%= link_to 'Show me all', recipes_path %>
    </div>
  </div>
</div>